### create a note (data is base64 encoded)
POST {{host}}/api/notes
Content-Type: application/json

{
  "data": "aGVsbG8gd29ybGQK",
  "dontAsk": true
}

### get note' meta data by id where Pp7vG_gKfeoBEy6g17-_b is nonoid if a note
GET {{host}}/api/notes/HhijMoG-LnPG7yVO0kADZ
Content-Type: application/json

### get data and delete note
DELETE {{host}}/api/notes/HhijMoG-LnPG7yVO0kADZ
Content-Type: application/json

### debug put
PUT {{host}}/api/debug?hello=world
Content-Type: application/json

{"type":"default"}
