### debug put
PUT {{host}}/api/debug?hello=world
Content-Type: application/json

{"type":"default"}

### get one by id where Pp7vG_gKfeoBEy6g17-_b is nonoid if a note
GET {{host}}/api/notes/Pp7vG_gKfeoBEy6g17-_b
Content-Type: application/json

### get data by id where Pp7vG_gKfeoBEy6g17-_b is nonoid if a note
GET {{host}}/api/notes/Pp7vG_gKfeoBEy6g17-_b/data
Content-Type: application/json


### create one, data is base64 encoded
POST {{host}}/api/notes
Content-Type: application/json

{
  "data": "aGVsbG8gd29ybGQK"
}
