### debug put
PUT {{host}}/api/debug?hello=world
Content-Type: application/json

{"type":"default"}

### get one by id where vmJWLQsx is id and a5X2Up19G is password
GET {{host}}/api/notes/vmJWLQsx#a5X2Up19G
Content-Type: application/json

### create one
POST {{host}}/api/notes
Content-Type: application/json

{

  "encryptedData": "hellp"
}
